# Generated by Django 4.2.10 on 2024-03-01 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('authenticate_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
